# method / detaset / arch / pretrained
method: "standard"
dataset: "cifar10"
arch: "c12"
log_dir: "./exp/"
pretrain: ""

# optimization settings
optim: "sgd"
lr: 0.1
momentum: 0.0
lr_scheduler_type: "multistep"
lr_warmup_epoch: 0
lr_warmup_type: "linear"
lr_warmup_decay: 0.0
lr_end_factor: 0.0
weight_decay: 0.0000
adam_beta1: 0.9
adam_beta2: 0.999
rmsp_alpha: 0.99
batch_size: 1024
seed: 0
epoch: 10
